name: random_allocation
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - numba>=0.60.0
  - pip
  - pip:
    - dp_accounting>=0.4.4 